import { useState } from "react";
import { FileDown } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { ItineraryData } from "@/types/itinerary";
import { toast } from "sonner";

const safeSymbols: Record<string, string> = {
  INR: "INR ", EUR: "EUR ", USD: "$", GBP: "GBP ", JPY: "JPY ", THB: "THB ",
  AUD: "A$", CAD: "C$", SGD: "S$", MYR: "MYR ", NZD: "NZ$",
};

function safe(text: string): string {
  return text
    .replace(/→/g, "->")
    .replace(/←/g, "<-")
    .replace(/₹/g, "INR ")
    .replace(/[^\x00-\x7F]/g, "");
}

export function ExportPDF({ itinerary }: { itinerary: ItineraryData }) {
  const [loading, setLoading] = useState(false);

  const handleExport = async () => {
    setLoading(true);
    try {
      const { default: jsPDF } = await import("jspdf");
      const symbol = safeSymbols[itinerary.currency] || itinerary.currency || "$";
      const doc = new jsPDF();
      let y = 20;

      const checkPage = (needed: number) => {
        if (y + needed > 270) { doc.addPage(); y = 20; }
      };

      // Title
      doc.setFontSize(22);
      doc.setTextColor(33, 33, 33);
      doc.text(safe(itinerary.title || "Trip Itinerary"), 15, y);
      y += 10;

      // Duration
      if (itinerary.days) {
        doc.setFontSize(11);
        doc.setTextColor(100, 100, 100);
        const dur = `${itinerary.days} day${itinerary.days > 1 ? "s" : ""}${itinerary.nights ? `, ${itinerary.nights} night${itinerary.nights > 1 ? "s" : ""}` : ""}`;
        doc.text(dur, 15, y);
        y += 8;
      }

      doc.setDrawColor(180);
      doc.line(15, y, 195, y);
      y += 10;

      // Group by day
      const dayGroups: Record<number, typeof itinerary.legs> = {};
      itinerary.legs.forEach((leg) => {
        const day = leg.day || 1;
        if (!dayGroups[day]) dayGroups[day] = [];
        dayGroups[day].push(leg);
      });

      for (const [day, legs] of Object.entries(dayGroups).sort(([a], [b]) => Number(a) - Number(b))) {
        checkPage(20);
        doc.setFillColor(240, 240, 240);
        doc.roundedRect(14, y - 5, 182, 10, 2, 2, "F");
        doc.setFontSize(14);
        doc.setTextColor(40, 40, 40);
        doc.text(`Day ${day}`, 17, y + 2);
        y += 12;

        for (const leg of legs) {
          checkPage(25);
          // Title + cost
          doc.setFontSize(11);
          doc.setTextColor(33, 33, 33);
          const title = safe(leg.title);
          doc.text(`  ${title}`, 18, y);
          const costText = leg.cost > 0 ? `${symbol}${leg.cost}` : "Free";
          doc.text(costText, 190, y, { align: "right" });
          y += 5;

          doc.setFontSize(9);
          doc.setTextColor(100, 100, 100);

          if (leg.description) {
            const descLines = doc.splitTextToSize(safe(leg.description), 155);
            doc.text(descLines, 22, y);
            y += descLines.length * 4;
          }
          if (leg.from && leg.to) {
            doc.text(safe(`${leg.from} -> ${leg.to}`), 22, y);
            y += 4;
          }
          if (leg.time) {
            doc.text(safe(leg.time), 22, y);
            y += 4;
          }
          y += 4;
        }
        y += 4;
      }

      // Packing list
      if (itinerary.packingList && itinerary.packingList.length > 0) {
        checkPage(20);
        doc.setDrawColor(180);
        doc.line(15, y, 195, y);
        y += 8;
        doc.setFontSize(13);
        doc.setTextColor(40, 40, 40);
        doc.text("Packing List", 15, y);
        y += 7;
        doc.setFontSize(10);
        doc.setTextColor(60, 60, 60);
        for (const item of itinerary.packingList) {
          checkPage(6);
          doc.text(`- ${safe(item)}`, 20, y);
          y += 5;
        }
        y += 4;
      }

      // Total
      checkPage(20);
      doc.setDrawColor(180);
      doc.line(15, y, 195, y);
      y += 8;
      doc.setFontSize(14);
      doc.setTextColor(33, 33, 33);
      doc.text("Total Cost", 15, y);
      doc.text(`${symbol}${itinerary.totalCost}`, 190, y, { align: "right" });

      // Page numbers and footer
      const totalPages = doc.getNumberOfPages();
      for (let p = 1; p <= totalPages; p++) {
        doc.setPage(p);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(`Page ${p} of ${totalPages}`, 105, 290, { align: "center" });
        doc.text("Generated by TripMap Planner.ai", 195, 290, { align: "right" });
      }

      doc.save(`${(itinerary.title || "itinerary").replace(/\s+/g, "_")}.pdf`);
      toast.success("PDF downloaded!");
    } catch {
      toast.error("Failed to export PDF");
    } finally {
      setLoading(false);
    }
  };

  return (
    <Button variant="ghost" size="icon" onClick={handleExport} disabled={loading} title="Export as PDF" className="glass text-foreground">
      <FileDown className="w-4 h-4" />
    </Button>
  );
}
